# Resourcely Guardrail Validation 
# Used to validate your Terraform plans against Resourcely Guardrails

# The variables defined in this template are common defaults. If you need to configure them,
# simply add them to your project's .gitlab-ci.yml or your project's UI CI/CD variables.
# See https://docs.resourcely.com/getting-started/onboarding/ci-cd-setup/gitlab-pipelines for more information
variables:
  TF_DIRECTORY: $CI_PROJECT_DIR
  RESOURCELY_API_HOST: "https://api.resourcely.io"
  VCS: "gitlab"
  CHANGE_REQUEST_URL: $CI_MERGE_REQUEST_PROJECT_URL/-/merge_requests/$CI_MERGE_REQUEST_IID
  RESOURCELY_DEBUG: "false"

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: always
    - when: never

resourcely_guardrails:
  stage: test
  image: 
    name: ghcr.io/resourcely-inc/resourcely-cli:latest
    entrypoint: [""]
  script:
    - /resourcely-cli evaluate --vcs $VCS --change_request_url $CHANGE_REQUEST_URL --change_request_sha $CI_COMMIT_SHA $TF_DIRECTORY/plan.json
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  artifacts:
    paths:
      - $TF_DIRECTORY/plan.json
  allow_failure: true
