# This template runs the Resourcely guardrail validation job on your Terraform plan(s) created
# within Resourcely. It can be applied by adding the template to your .gitlab-ci.yml as follows
# include:
#   - remote: 'https://raw.githubusercontent.com/Resourcely-Inc/resourcely-gitlab-template/main/.resourcely.gitlab-ci.yml'
# See https://docs.gitlab.com/ee/ci/yaml/includes.html for usage examples

# Requires the following private variables to be configured:
# RESOURCELY_API_TOKEN: Your Resourcely API Token

# These variables can be overwritten in the .gitlab-ci.yml
# which imports this template
variables:
  TF_PLAN_DIRECTORY: $CI_PROJECT_DIR
  TF_PLAN_PATTERN: "plan*"
  CHANGE_REQUEST_URL: $CI_MERGE_REQUEST_PROJECT_URL/-/merge_requests/$CI_MERGE_REQUEST_IID
  RESOURCELY_API_HOST: "https://api.resourcely.io"
  RESOURCELY_IMAGE: "latest"
  RESOURCELY_DEBUG: "false"

resourcely_guardrails:
  stage: test
  image: 
    name: ghcr.io/resourcely-inc/resourcely-cli:$RESOURCELY_IMAGE
    entrypoint: [""]
  script:
    - /resourcely-cli evaluate --change_request_url $CHANGE_REQUEST_URL --change_request_sha $CI_COMMIT_SHA --plan $TF_PLAN_DIRECTORY/plan.json
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  allow_failure: true